### ISSUE TITLE
[Enhancement]: Separate DNS server and Nginx containers

### ISSUE THREAD

**Issue by MatthewL246** [PretendoNetwork/SSSL-DNS#1]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

I think it would make more sense to run the DNS server and Nginx in separate containers. For example, someone might have a use for Nginx with support for old TLS versions, but they might not need the DNS server (suppose they are using something like PiHole already and prefer to configure DNS spoofing there). It would also be convenient to provide an example Docker Compose file to build and run both containers.

### Any other details to share? (OPTIONAL)

I would be willing to work on this myself if it is approved.

**Comment by jonbarrow** [comment]
You can still use a PiHole for DNS if you wish, I've done it for local testing. But this sounds fine to me
