### ISSUE TITLE
[Enhancement]: Use JSON for configuring DNS lookups instead of ENV

### ISSUE THREAD

**Issue by EmmettCarpenter** [PretendoNetwork/SSSL-DNS#6]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

Use a JSON file to configure the DNS map instead of ENV variables.

EX:
```
{
    "conntest.nintendowifi.net":  "127.0.0.1"
}
```

### Any other details to share? (OPTIONAL)

I am assuming that there is a deployment reason for using ENV values, but this would be a more graceful way to solve #3 .

**Comment by jonbarrow** [comment]
The reason environment variables are used over configuration files is to provide easier integration with Docker. Using configuration files like as suggested here would require the physical file to be moved into the container for the server to use the data. Compared to environment variables, which can be defined by the host

**Comment by EmmettCarpenter** [comment]
Gotcha, makes sense.
